apiVersion: v1
kind: Secret
metadata:
  name: tekton-hub-api
type: Opaque
stringData:
  GH_CLIENT_ID: 'asd'
  GH_CLIENT_SECRET: 'asd'
  GHE_URL: ''
  GL_CLIENT_ID: ''
  GL_CLIENT_SECRET: ''
  GLE_URL: ''
  BB_CLIENT_ID: ''
  BB_CLIENT_SECRET: ''
  JWT_SIGNING_KEY: 'asd'
  ACCESS_JWT_EXPIRES_IN: '1d'
  REFRESH_JWT_EXPIRES_IN: '1d'
  AUTH_BASE_URL: ''
