apiVersion: v1
kind: Secret
metadata:
  name: api
  namespace: tekton-hub
type: Opaque
stringData:
  GH_CLIENT_ID: "0fc62745613381db76e7"
  GH_CLIENT_SECRET: "9633e6b96e781310a9d7e3a7ad6ad9f101d7b619"
  JWT_SIGNING_KEY: "tekton-hub"
